### ISSUE TITLE
Split this into two papers?

### ISSUE THREAD

**Issue by fbartolic** [fbartolic/volcano#15]
Currently the paper has two somewhat distinct parts. The first part concerns the question of how to infer static maps from occultation light curves of Io with starry. It introduces pixels/sphixels as a way of ensuring positivity of the maps, it discusses different prior choices,  fixing ringing artefacts via Gaussian filtering and the differences between optimization, VI and HMC for fitting the model. The second part generalizes the static model to the case where we the map for each light curve is different. We tackle this problem with NMF in a Bayesian setting. The common thread between both parts is that we use the same Io dataset as a testbed fo our models. The NMF model builds on the first part. Both parts are relevant to stars/exoplanets but the first part more so. 

If we decide to split the paper into two, how should we do it? Here's a rough table of contents for both papers:

**Paper 1 - Static model**:
- background on Io, IRTF dataset
- computing the ephemeris, effective radius of Jupiter, information content of different kinds of light curves (occultations, phase curves, both)
- sphixels/pixels
- influence of different priors on sphixels on the inferred map
-  smoothing kernel
- fitting simulated pair of light curves
- fitting  multiple pairs of IRTF light curves, recovering Loki
- comparison between different inference algorithms - MAP, VI, HMC
- fitting a simulated JWST dataset of volcanic super Earth?

Possible additions:
- mutual occultations in reflected light
- comparison to parametric models where we fit for location, size and amplitude of a fixed nr. of spots
- simulating uncertainty in orbital parameters and investigating the degeneracies between those parameters and map features

**Paper 2 - Dynamic model**:
- repeated discussion of Io, dataset
- literature review on NMF, discussion of degeneracies
- priors for NMF
- inferring map and components for simulated data, recovering time variability in some sense, sensitivity to nr. of components, degree of map etc.
- comparison to a simpler model such as Taylor expanding SH coefficients or pixels
- apply model to IRTF data, test sensitivity to fitting different subsets of the data, plot time series of intensities for interesting specific regions on the surface

Possible additions:
- try non Bayesian approach with off the shelf optimizers for NMF such as [proxmin](https://github.com/pmelchior/proxmin)

Given that we'd be mostly focused on Io in both papers, I'm leaning towards a paper 1/paper 2 split rather than having two distinct papers. What are your thoughts  @rodluger  @dfm ?

**Comment by rodluger** [comment]
@fbartolic This sounds great! I think the split makes sense as you've laid it out. Some notes:

- Fitting a simulated dataset with JWST is a great idea for Paper 1. It shouldn't be hard to do! All we need to do is add some realistic JWST noise. Jacob Lustig-Yaeger wrote a [script](https://github.com/rodluger/planetplanet/blob/master/planetplanet/detect/jwst.py) to do that for my planet-planet occultations paper, which should be straightforward to adapt. I'm happy to help with this.
- I wouldn't worry about mutual occultations in reflected light for Paper 1. That can be its own paper, since the whole methodology for fitting it with starry is novel. Perhaps even paper 3 in the series, if you're ever up to the task?
- I *do* think the comparison to a parametric model is an important thing to think about for Paper 1. That will probably be the question on everyone's mind when using this paper: why use spherical harmonics? Why not just fit for the positions of the volcanoes directly? I don't think it should be too hard to implement a forward model for this. You can even use starry, as follows: pixelize the surface of the star at some resolution, add your parametric volcanoes, then transform to Ylms to compute the flux. This is very similar to your sphixels approach, so I bet it should be easy to implement.
- Your third point about investigating the uncertainty in orbital parameters is also a good one, but I think that, too, could be its own paper. There are *lots* of papers in the exoplanet mapping community where they take the orbital solution for granted, so we could write a standalone impactful paper showing the biases this can lead to. I don't think this has been done at all, and I think it would be much more impactful if we detached it from the Io plotline.

**Comment by rodluger** [comment]
Oh! And I think paper 2 is just as applicable to exoplanets! Time variability due to weather is going to be a HUGE obstacle when it comes to mapping exoplanets. Also, planets like 55 Cancri e could be true Io analogues, so it's definitely worth drawing the connection there, too.

**Comment by fbartolic** [comment]
Ok, I'll create another repo for paper 2 and reorganise everything unless @dfm objects.

> I wouldn't worry about mutual occultations in reflected light for Paper 1. That can be its own paper, since the whole methodology for fitting it with starry is novel. Perhaps even paper 3 in the series, if you're ever up to the task?

Haha, I doubt I'll have time for that :) 

> I do think the comparison to a parametric model is an important thing to think about for Paper 1. That will probably be the question on everyone's mind when using this paper: why use spherical harmonics? Why not just fit for the positions of the volcanoes directly? I don't think it should be too hard to implement a forward model for this. You can even use starry, as follows: pixelize the surface of the star at some resolution, add your parametric volcanoes, then transform to Ylms to compute the flux. This is very similar to your sphixels approach, so I bet it should be easy to implement.

Or we can avoid the sphixels entirely and just fit for an $l=30$ map and the parameters going into `add_spot`. I'll try that first.

**Comment by dfm** [comment]
This all sounds great!

**Comment by fbartolic** [comment]
Closing this, Paper II repo is [here](https://github.com/fbartolic/volcano_nmf).
