### ISSUE TITLE
Test at which point evaluation of the marginalized likelihood becomes more expensive than the unmarginalized likelihood

### ISSUE THREAD

**Issue by fbartolic** [fbartolic/volcano#9]

**Comment by fbartolic** [comment]
I timed the evaluation of a theano function returning total log probability evaluated at `model.test_point` for the model in [this](https://rodluger.github.io/starry/v1.0.0/notebooks/EclipsingBinary_FullSolution_Painful.html) tutorial and compared it to the same model with analytically marginalized SH coefficients as a function of the degree of the map and I get the following plot:

![image](https://user-images.githubusercontent.com/18243408/76550720-f780a100-6468-11ea-8dc3-2b8b0a505341.png)

It looks like the marginalized model is consistently faster than the one which includes the SH coefficients as parameters, even for very high degree maps. The difference in sampling performance between the two models should also increase with dimension because the number of parameters in the second model is constant.

**Comment by dfm** [comment]
I think that the plot actually (as it should) shows that the marginalized model is consistently *slower* (larger wall time should be worse!). And the computational cost of the marginalization will scale as the cube of the number of coefficients whereas the model evaluation will scale as the square. This means that it's not obvious how this will scale in a full MCMC. It's also not quite true that the sampling cost will scale the same way because there can be issues with convergence when using marginalized model in my experience. I think the real test will be to compare the full end-to-end sampling performance of the two methods!

**Comment by fbartolic** [comment]
Sorry I completely mixed up the ordering in my head! Yes that makes sense. 

>It's also not quite true that the sampling cost will scale the same way because there can be issues with convergence when using marginalized model in my experience.  

Can you elaborate on this point? In the two examples in starry docs, is the order of magnitude sampling performance difference between the two models (in favor of marginalizing) mostly due to scaling of HMC with the dimension of the parameter space?

**Comment by dfm** [comment]
I haven't tried with starry directly, but I have found with other similar linear models that the NUTS sampler mixes better when all the weights are included as parameters rather than marginalized. Even though this is many more parameters, the runtime still works out to be shorter because of the faster mixing. All I'm saying is that it's not obvious one way or another what method will be best for our current data without doing the experiment! We should probably keep support for both.

**Comment by fbartolic** [comment]
Yeah I agree that it's not at all obvious what the runtime will be. I'll run full sampling with maps of different degrees and see how the runtime changes.

**Comment by fbartolic** [comment]
Not relevant anymore, we're optimizing/sampling in all parameters. Closing for now.
